### ISSUE TITLE
can't load model

### ISSUE THREAD

**Issue by segalinc** [LyazS/comfyui-anime-seg#1]
when running ComfyUI I get
`INVALID_PROTOBUF : Load model from ComfyUI/custom_nodes/comfyui-anime-seg/model/isnetis.onnx failed:Protobuf parsing failed.`

**Comment by katyo** [comment]
@segalinc I have same issue.

**Comment by LyazS** [comment]
check if the onnx exist. Or just download it manually and put it in the place.
